### PR TITLE
add pull request template

### PR DESCRIPTION
**Pull request by Slixe**
Add a Pull-request template for easier understanding.

Im am contributing & releasing the code under DERO Research License (which can be found [here](https://raw.githubusercontent.com/deroproject/derohe/main/license.txt)).

### CODE REVIEW

**Comment by deroholic** [comment]
Suggest you add another type of change, something like:

 [ ] Major Change (Requires Hard Fork)

**Comment by Nelbert442** [comment]
Potentially also worth adding to the "Which part is impacted?" 

- [ ] Explorer 
- [ ] Simulator

**Comment by CaptainDero** [comment]
Can we change the location of this template file to main directory.

**Comment by Slixe** [comment]
> Potentially also worth adding to the "Which part is impacted?"
> 
> * [ ]  Explorer
> * [ ]  Simulator

Sure, I will add it.



> Can we change the location of this template file to main directory.

It would be better to let it in .github folder so GitHub will automatically apply the pull request template when someone create pull request. Which is much easier to anyone who want to contribute easily.

**Pull request merged**
